# tasks file
---
- name: install | dependencies  # noqa args[module]
  ansible.builtin.apt:
    name: "{{ latest_git_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - latest-git-install-dependencies
