# tasks file
---
- include: repository.yml
  tags:
    - configuration
    - latest-git
    - latest-git-repository

- include: install.yml
  tags:
    - configuration
    - latest-git
    - latest-git-install
