# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - latest-git
    - latest-git-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - latest-git
    - latest-git-install
