# tasks file for latest-git
---
- name: add repository from PPA and install its signing key
  apt_repository:
    repo: 'ppa:git-core/ppa'
    update_cache: true
  tags:
    - configuration
    - latest-git
    - latest-git-add-repository

- name: install
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ latest_git_dependencies }}"
  tags:
    - configuration
    - latest-git
    - latest-git-install
