# tasks file
---
- name: repository | dependencies
  apt:
    name: "{{ latest_git_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - latest-git-repository-dependencies

- name: repository | add
  apt_repository:
    repo: 'ppa:git-core/ppa'
    update_cache: true
    mode: 0644
  tags:
    - latest-git-repository-add
